# Install elasticsearch plugin
- name: Install base configuration
  template:
    dest: /etc/td-agent/td-agent.conf
    src: etc/td-agent/client-td-agent.conf.j2
  notify: restart td-agent

- name: Install application configurations
  template:
    dest: /etc/td-agent/config.d/{{ item }}.conf
    src: etc/td-agent/config.d/{{ item }}.conf.j2
  with_items: "{{ fluentd_apps }}"
  notify: restart td-agent
