---
# Red Hat Installation
- name: Add TreasureData Repository
  yum_repository:
    name: treasuredata
    file: td
    description: TreasureData
    baseurl: http://packages.treasuredata.com/2/redhat/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: Install td-agent RPM
  yum:
    name: td-agent
    state: installed

- name: Manage td-agent service
  service: 
    name: td-agent
    state: started 
    enabled: yes

- name: Open fluent UDP port
  firewalld:
    port: 24224/udp
    premanent: true
    state: enabled
    immediate: true

- name: Open fluent TCP port
  firewalld: 
    port: 24224/tcp
    permanent: true
    state: enabled 
    immediate: true

- name: Open fluent HTTP port
  firewalld: 
    port: 8888/tcp 
    permanent: true 
    state: enabled 
    immediate: true
